# Generated by Django 4.0.1 on 2022-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipeimage',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
